name: tf_photo_avatar
description: Tf_photo_avatar is the package for Tenfins Circular Photo Avatar Widget, i.e., TfPhotoAvatar. It supports Cached and Non-cached Image options.
version: 1.0.0
homepage: https://github.com/rahul-badgujar/tf_photo_avatar_flutter_package.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/gif/
    - assets/icons/
